### ISSUE TITLE
changement_COG_varNum

### ISSUE THREAD

**Issue by Maryam-VD** [antuki/COGugaison#10]
Hello! Thanks for this package. I have an issue. I am trying to manage the official geographic codes in a data frame. For Many data frames the code "changement_COG_varNum" works pretty well. However, with one of my data frames it says:
> test <- changement_COG_varNum(table_entree=communes_cz_19,annees=c(2012:2019),codgeo_entree="COG12",agregation=F,libgeo=F,donnees_insee=T)

Error in Ops.data.frame(provisoire[, c(var_num, "ratio")], provisoire[,  : 
  ‘*’ only defined for equally-sized data frames

The data frame "communes_cz_19" is a sf containing the geometry of communes in France on 2012. I thought it might be the problem with the geometry variable, so I extracted the COG codes in another data frame (result) and tried again. Now it says:

> test <- changement_COG_varNum(table_entree=result,annees=c(2012:2019),codgeo_entree="COG12",agregation=F,libgeo=F,donnees_insee=T)

Error in (provisoire[, c(var_num, "ratio")] * provisoire[, "ratio"])[,  : 
  incorrect number of dimensions

What am I doing wrong? What should I do?

**Comment by Maryam-VD** [comment]
I put a code to simulate the first 10 rows of "result":
result <- tribble(~COG12,c("14078","57324","14144","76496","80481","02129","78158","51336","50160","64129"))
result <- unnest(result,COG12)
result$COG19 <- result$COG12
result <- as.data.frame(result)
result <- changement_COG_varNum(table_entree=result,annees=c(2012:2019),codgeo_entree="COG19",agregation=F,libgeo=F,donnees_insee=T)

Error in (provisoire[, c(var_num, "ratio")] * provisoire[, "ratio"])[,  : 
  incorrect number of dimensions

**Comment by antuki** [comment]
Hi Maryam VD, 
Thank for using COGugaison. 
I'm sorry but I don't quite understand why you want to use COG_varNum in your example and what you want to do exactly. The use of COG_varNum is to change the year of a numeric variable such as the population, number of houses... in each municipality. In your example you just have the codes of the municipalities but no variable. Maybe you just want to have a table of the different movement between 2012 and 2019, for that you can look at the datasets in the package called "PASSAGE_2018_2019" for example. 
Here is another example adapted to COG_varNum : 

````
> library (COGugaison)
> library(tidyverse)
> result <- exemple_popcom
> head(result)
  CODGEO                  LIBGEO P12_POP SUPERF    typoA typoB
1  01001 L'Abergement-Clémenciat     777     16 CLASSE 2     F
2  01002   L'Abergement-de-Varey     235      9 CLASSE 3     D
3  01004       Ambérieu-en-Bugey   14233     25 CLASSE 1     B
4  01005     Ambérieux-en-Dombes    1642     16 CLASSE 3     F
5  01006                 Ambléon     110      6 CLASSE 4     E
6  01007                Ambronay    2437     34 CLASSE 5     A
> result_2 <- changement_COG_varNum(table_entree = result, annees = c(2014:2017), 
codgeo_entree ="CODGEO", agregation = TRUE, libgeo = F, donnees_insee =T)
> head(result_2)
  CODGEO P12_POP SUPERF
1  01001     777     16
2  01002     235      9
3  01004   14233     25
4  01005    1642     16
5  01006     110      6
6  01007    2437     34
````

You can see other examples here:
https://antuki.github.io/COGugaison/articles/COGugaison.html

Does it help ?

**Comment by Maryam-VD** [comment]
Thanks a lot for your reply.
For now I solved my problem by finding the corresponding insee codes of 2012 for my data on 2019. 
But based on your answer, I am not sure if I understand exactly how the code works then! At least from what you show here, I don't see the difference between the result and result_2.
Well, my data are gathered from 2009 to 2019 and the insee codes do not belong to only one year. I need to find the ratio of the number of data point I have in each year w.r.t. number of houses being built before 1990 in that year. And then I need to relate them to the climate zones and plot them on the map. So my idea was to get the geography and housing information on 2019 and solve a bit simplified problem.
I couldn't find the simplified shape file for the map of France for 2019 (I have it for 2012). And I have a data set of housing information on 2011 and 2016 regarding the insee codes of 2019. 
I think looking at the PASSAGE packages would be so time consuming, and the ``changement_COG_varNum" changes my insee codes properly (I suppose!). Though it can help me find the housing information in different years, right? 
But are you telling me that my code is changing my other variables in my data set as well? These data are NOT gathered by INSEE.
And one more question: is there anyway to change the geometry of a sf data frame of one year to another year?
I hope it is more clear now!

**Comment by antuki** [comment]
Here are the answers of your different questions:

* about the example I gave. Indeed you couldn't see any difference between the two datasets because the head function only shows the first rows so sorry it was not very clear. But if you filter on row where event happened between the 2 years, you can see for example that the row are added for merges : 

````
> library (COGugaison)
> library(tidyverse)
> result <- exemple_popcom
> result_2 <- changement_COG_varNum(table_entree = result, annees = c(2014:2017), 
codgeo_entree ="CODGEO",
 agregation = TRUE, libgeo = F, donnees_insee =T)
> head(result %>% filter(CODGEO%in%c("14178","14474")))
  CODGEO               LIBGEO P12_POP SUPERF    typoA typoB
1  14178               Corbon      66      4 CLASSE 2     F
2  14474 Notre-Dame-d'Estrées     171      7 CLASSE 4     B
> head(result_2 %>% filter(CODGEO%in%c("14178","14474")))
  CODGEO P12_POP SUPERF
1  14474     237     11

````

* your issue is totally something COGugaison can help you with. Nevertheless you will see that you will have to do some additionnal work to have the precise answer to your issue but it definitely can help you

* about the shapefiles, i have another package on github called CARTElette where you can find the shapefile of 2019 French administrative divisions : https://github.com/antuki/CARTElette/tree/master/couches_carto/IGN/COG2019 See COM_2019_CARTElette for the municipalities. but you can build your own shapefiles on R using the package `sf` (for spatial features) and `dplyr` (especially the function summarize which can help gathering some municipalities together on a shapefile)

* and yes when you use COG_varNum you basically change your own datasets. If you just need your own "PASSAGE_2012_2019" you just have to bind the rows of the PASSAGE_XXXX_XXXX datasets juste like in this example:

````
> library (COGugaison)
> library(tidyverse)
> PASSAGE_2017_2019 <- bind_rows(
PASSAGE_2017_2018 %>% setNames( c("old_code","new_code",colnames(PASSAGE_2017_2018)[-c(1:2)]) ),

PASSAGE_2018_2019 %>% setNames( c("old_code","new_code",colnames(PASSAGE_2018_2019)[-c(1:2)]) )
 )
````

Finally, can I ask you where you work and how did you discover the package ? You can anwer me on my twitter account @antuki13 it would be easier to discuss or by email if you don't have twitter : kim.demarty@laposte.net
